import type { Metadata } from "next";
import "./globals.css";
import { DefaultFooter, DefaultHeader } from "@/components/globals";

export const metadata: Metadata = {
  title: "Arcade Productions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DefaultHeader />
        {children}
        <DefaultFooter />
      </body>
    </html>
  );
}
